### ISSUE TITLE
Populate svg root attributes as props

### ISSUE THREAD

**Issue by onemanstartup** [janjakubnanista/svg-jsx-loader#1]
Is it possible to do this?
I wanted to get width and height information from svg root in parent element to set viewBox based on this numbers.

**Comment by janjakubnanista** [comment]
@onemanstartup I don't think I understand, please provide an example - you have an existing SVG file that has `width` and `height` set and you would like to set `viewBox` on the same element based on these numbers?

**Comment by janjakubnanista** [comment]
Closing due to no response.
