### ISSUE TITLE
Use stateless functional components for templates

### ISSUE THREAD

**Issue by frenzzy** [janjakubnanista/svg-jsx-loader#2]
> This pattern is designed to encourage the creation of these simple components that should comprise large portions of your apps. In the future, we’ll also be able to make performance optimizations specific to these components by avoiding unnecessary checks and memory allocations.
> https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

Example:

``` js
import React from 'react';

const SvgComponentName = (props) => (
  <svg width="100" height="100" viewBox="0 0 10 10" {...props}>
    <rect width="10" height="10" />
  </svg>
);

export default SvgComponentName;
```

**Comment by janjakubnanista** [comment]
I wonder how deep this should go - it's simple to add this "function wrapper" around the SVG string, the tricky part is the rest. Should we support CommonJS? ES6? Both? Should we add component name option? etc.

**Comment by janjakubnanista** [comment]
This is easy to implement but adds no value - the generated files are pushed through Webpack loaders anyway so their structure is of very little significance. However if you have a usecase for this I'll be glad to help @frenzzy.
